name: et_eats
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  intl: 0.19.0
  flutter_layout_grid: 2.0.6
  flutter_rating_bar: 4.0.1
  go_router: 14.1.1
  flutter_riverpod: 2.5.1
  rxdart: 0.27.7
  auto_size_text: ^3.0.0
  url_strategy: ^0.3.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
